export const areas = ["Linguagem", "Cognição", "Socialização", "Autocuidados", "Desenvolvimento motor"] as const;
export type Area = (typeof areas)[number];

export type Student = { id: string; name: string; initials: string; age: string; context: string; lastUpdate: string };
export type Indicator = { id: string; area: Area; label: string; status: "potencial" | "em-desenvolvimento" | "consolidado" };
export type Skill = { id: string; area: Area; name: string; indicatorIds: string[] };
export type Objective = { id: string; skillId: string; title: string; horizon: string };
export const documentTypes = ["PEI", "PDI", "PAEE"] as const;
export type DocumentType = (typeof documentTypes)[number];
export type InstitutionalDocument = { type: DocumentType; name: string; description: string; caution: string };
export type SuggestionDecision = "pending" | "selected" | "edited" | "rejected";
export const activityModalities = ["Individual", "Coletiva"] as const;
export type ActivityModality = (typeof activityModalities)[number];
export const complexityLevels = ["Inicial", "Intermediária", "Avançada"] as const;
export type ComplexityLevel = (typeof complexityLevels)[number];
export const editorialStates = ["Rascunho demonstrativo", "Em revisão demonstrativa"] as const;
export type EditorialState = (typeof editorialStates)[number];
export type ComplexityVariation = { level: ComplexityLevel; description: string };
export const activityDomains = ["Comunicação e expressão", "Interação e participação", "Autonomia e rotina", "Habilidades acadêmicas funcionais"] as const;
export type ActivityDomain = (typeof activityDomains)[number];
export type Activity = {
  id: string;
  domain: ActivityDomain;
  title: string;
  description: string;
  purpose: string;
  relatedSkillIds: string[];
  relatedObjectiveIds: string[];
  applicationContext: string;
  indicativeAgeOrStage: string;
  modality: ActivityModality;
  materials: string[];
  estimatedDuration: string;
  supportLevel: string;
  complexityLevel: ComplexityLevel;
  complexityVariations: ComplexityVariation[];
  possibleAdaptations: string[];
  accessibilityResources: string[];
  applicationGuidance: string[];
  observationElements: string[];
  resultRecording: string;
  possibleNextSteps: string[];
  authorship: string;
  license: string;
  editorialState: EditorialState;
  version: string;
  reviewDate: string;
  /** Campos de compatibilidade da apresentação anterior; remover quando as demais prévias migrarem. */
  name: string; summary: string; area: Area; skillId: string; objectiveId: string; ageRange: string;
  environment: string; preparation: string; steps: string[]; adaptations: string[];
  observationCriterion: string; source: string; author: string; reviewStatus: string;
};

export type ActivityFilters = {
  skillId?: string;
  objectiveId?: string;
  context?: string;
  modality?: ActivityModality;
  complexityLevel?: ComplexityLevel;
  adaptation?: string;
  accessibilityResource?: string;
};
